In [1]:
import numpy as np


In [2]:
a1=np.array([1,2,4,3])

In [3]:
a1


array([1, 2, 4, 3])

In [4]:
a1.dtype

dtype('int32')

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2=a1**2

In [7]:
a2

array([ 1,  4, 16,  9], dtype=int32)

In [8]:
a2

array([ 1,  4, 16,  9], dtype=int32)

In [11]:
a3=np.array([[1,2,3,4],[5,6,7,8]])

In [12]:
a3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
a3.shape

(2, 4)

In [15]:
np.unique(a3)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
a4=np.ones((3,2,4))

In [17]:
a4

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [18]:
a3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
a3*a4

array([[[1., 2., 3., 4.],
        [5., 6., 7., 8.]],

       [[1., 2., 3., 4.],
        [5., 6., 7., 8.]],

       [[1., 2., 3., 4.],
        [5., 6., 7., 8.]]])

In [20]:
a5=np.ones((3,3,3))

In [21]:
a5

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [22]:
a4*a5

ValueError: operands could not be broadcast together with shapes (3,2,4) (3,3,3) 

In [27]:
a4[:2,:2,:3]*a6[:2,:2,:]

array([[[4., 1., 9.],
        [6., 3., 5.]],

       [[0., 8., 2.],
        [5., 6., 8.]]])

In [24]:
a6=np.random.randint(0,10,size=(3,3,3))

In [25]:
a6

array([[[4, 1, 9],
        [6, 3, 5],
        [5, 7, 0]],

       [[0, 8, 2],
        [5, 6, 8],
        [0, 9, 5]],

       [[3, 9, 1],
        [1, 4, 6],
        [0, 6, 4]]])

In [30]:
np.random.seed(1)
ws=np.random.randint(10,size=(5,3))
ws

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]])

In [31]:
import pandas as pd

In [33]:
weekly_sales=pd.DataFrame(ws,index=['Mon','tue','wed','thu','fri'],columns=['Ferrari','Bmw','Audi'])
weekly_sales

Ferrari  Bmw  Audi
Mon        5    8     9
tue        5    0     0
wed        1    7     6
thu        9    2     4
fri        5    2     4

In [34]:
pri=np.array([200000,3000000,40000000])
pri

array([  200000,  3000000, 40000000])

In [38]:
prices=pd.DataFrame(pri.reshape((1,3)),index=['Price'],columns=['Ferrari','Bmw','Audi'])
prices

Ferrari      Bmw      Audi
Price   200000  3000000  40000000

In [40]:
total=ws.dot(pri)
total

array([385000000,   1000000, 261200000, 167800000, 167000000])

In [45]:
prices.shape

(1, 3)

In [44]:
weekly_sales.shape

(5, 3)

In [48]:
total_sale=prices.dot(weekly_sales.T) 
total_sale

Mon      tue        wed        thu        fri
Price  385000000  1000000  261200000  167800000  167000000

In [50]:
weekly_sales['Total (Rs)'] = total_sale.T

In [51]:
weekly_sales

Ferrari  Bmw  Audi  Total (Rs)
Mon        5    8     9   385000000
tue        5    0     0     1000000
wed        1    7     6   261200000
thu        9    2     4   167800000
fri        5    2     4   167000000

In [53]:
weekly_sales.to_csv("Car_sales.csv")

![]("Car_sales.csv")

![]("Car_sales.csv")

<img src="images/panda.png" />

In [64]:
import matplotlib.image as image

In [66]:
panda=image.imread("images/panda.png")

In [67]:
panda.dtype

dtype('float32')

In [68]:
type(panda)

numpy.ndarray

In [69]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [70]:
panda.size

24465000

In [71]:
panda.ndim

3

In [72]:
panda.shape

(2330, 3500, 3)